export default [
  ['Math', 'Math', () => import('../docs/Math.md')],

  '属性',
  ['Math.E', 'E', () => import('../docs/E.md')],
  ['Math.LN2', 'LN2', () => import('../docs/LN2.md')],
  ['Math.LN10', 'LN10', () => import('../docs/LN10.md')],
  ['Math.LOG2E', 'LOG2E', () => import('../docs/LOG2E.md')],
  ['Math.LOG10E', 'LOG10E', () => import('../docs/LOG10E.md')],
  ['Math.PI', 'PI', () => import('../docs/PI.md')],
  ['Math.SQRT1_2', 'SQRT1_2', () => import('../docs/SQRT1_2.md')],
  ['Math.SQRT2', 'SQRT2', () => import('../docs/SQRT2.md')],

  '方法',
  ['Math.abs(x)', 'abs', () => import('../docs/abs.md')],
  ['Math.acos(x)', 'acos', () => import('../docs/acos.md')],
  ['Math.acosh(x) [es6]', 'acosh', () => import('../docs/acosh.md')],
  ['Math.asin(x)', 'asin', () => import('../docs/asin.md')],
  ['Math.asinh(x) [es6]', 'asinh', () => import('../docs/asinh.md')],
  ['Math.atan(x)', 'atan', () => import('../docs/atan.md')],
  ['Math.atanh(x) [es6]', 'atanh', () => import('../docs/atanh.md')],
  ['Math.atan2(x, y)', 'atan2', () => import('../docs/atan2.md')],
  ['Math.cbrt(x) [es6]', 'cbrt', () => import('../docs/cbrt.md')],
  ['Math.ceil(x)', 'ceil', () => import('../docs/ceil.md')],
  ['Math.clz32(x) [es6]', 'clz32', () => import('../docs/clz32.md')],
  ['Math.cos(x)', 'cos', () => import('../docs/cos.md')],
  ['Math.cosh(x) [es6]', 'cosh', () => import('../docs/cosh.md')],
  ['Math.exp(x)', 'exp', () => import('../docs/exp.md')],
  ['Math.expm1(x) [es6]', 'expm1', () => import('../docs/expm1.md')],
  ['Math.floor(x)', 'floor', () => import('../docs/floor.md')],
  ['Math.fround(x) [es6]', 'fround', () => import('../docs/fround.md')],
  ['Math.hypot() [es6]', 'hypot', () => import('../docs/hypot.md')],
  ['Math.imul(x) [es6]', 'imul', () => import('../docs/imul.md')],
  ['Math.log(x)', 'log', () => import('../docs/log.md')],
  ['Math.log1p(x) [es6]', 'log1p', () => import('../docs/log1p.md')],
  ['Math.log10(x) [es6]', 'log10', () => import('../docs/log10.md')],
  ['Math.log2(x) [es6]', 'log2', () => import('../docs/log2.md')],
  ['Math.max()', 'max', () => import('../docs/max.md')],
  ['Math.min()', 'min', () => import('../docs/min.md')],
  ['Math.pow(x,y)', 'pow', () => import('../docs/pow.md')],
  ['Math.random()', 'random', () => import('../docs/random.md')],
  ['Math.round(x)', 'round', () => import('../docs/round.md')],
  ['Math.sign(x) [es6]', 'sign', () => import('../docs/sign.md')],
  ['Math.sin(x)', 'sin', () => import('../docs/sin.md')],
  ['Math.sinh(x) [es6]', 'sinh', () => import('../docs/sinh.md')],
  ['Math.sqrt(x)', 'sqrt', () => import('../docs/sqrt.md')],
  ['Math.tan(x)', 'tan', () => import('../docs/tan.md')],
  ['Math.tanh(x) [es6]', 'tanh', () => import('../docs/tanh.md')],
  ['Math.toSource()', null, null],
  ['Math.trunc(x) [es6]', 'trunc', () => import('../docs/trunc.md')]
];
