export default [
  ['Date', 'Date', () => import('../docs/Date.md')],

  '属性',
  ['Date.prototype', 'prototype', () => import('../docs/prototype.md')],
  ['Date.length', 'length', () => import('../docs/length.md')],

  '方法',
  ['Date.now()', 'now', () => import('../docs/now.md')],
  ['Date.parse()', 'parse', () => import('../docs/parse.md')],
  ['Date.UTC()', 'UTC', () => import('../docs/UTC.md')],

  'Getter方法',
  ['getDate()', 'getDate', () => import('../docs/getDate.md')],
  ['getDay()', 'getDay', () => import('../docs/getDay.md')],
  ['getFullYear()', 'getFullYear', () => import('../docs/getFullYear.md')],
  ['getHours()', 'getHours', () => import('../docs/getHours.md')],
  ['getMilliseconds()', 'getMilliseconds', () => import('../docs/getMilliseconds.md')],
  ['getMinutes()', 'getMinutes', () => import('../docs/getMinutes.md')],
  ['getMonth()', 'getMonth', () => import('../docs/getMonth.md')],
  ['getSeconds()', 'getSeconds', () => import('../docs/getSeconds.md')],
  ['getTime()', 'getTime', () => import('../docs/getTime.md')],
  ['getTimezoneOffset()', 'getTimezoneOffset', () => import('../docs/getTimezoneOffset.md')],
  ['getUTCDate()', 'getUTCDate', () => import('../docs/getUTCDate.md')],
  ['getUTCDay()', 'getUTCDay', () => import('../docs/getUTCDay.md')],
  ['getUTCFullYear()', 'getUTCFullYear', () => import('../docs/getUTCFullYear.md')],
  ['getUTCHours()', 'getUTCHours', () => import('../docs/getUTCHours.md')],
  ['getUTCMilliseconds()', 'getUTCMilliseconds', () => import('../docs/getUTCMilliseconds.md')],
  ['getUTCMinutes()', 'getUTCMinutes', () => import('../docs/getUTCMinutes.md')],
  ['getUTCMonth()', 'getUTCMonth', () => import('../docs/getUTCMonth.md')],
  ['getUTCSeconds()', 'getUTCSeconds', () => import('../docs/getUTCSeconds.md')],
  ['getYear() [已废弃]', 'getYear', () => import('../docs/getYear.md')],

  'Setter方法',
  ['setDate()', 'setDate', () => import('../docs/setDate.md')],
  ['setFullYear()', 'setFullYear', () => import('../docs/setFullYear.md')],
  ['setHours()', 'setHours', () => import('../docs/setHours.md')],
  ['setMilliseconds()', 'setMilliseconds', () => import('../docs/setMilliseconds.md')],
  ['setMinutes()', 'setMinutes', () => import('../docs/setMinutes.md')],
  ['setMonth()', 'setMonth', () => import('../docs/setMonth.md')],
  ['setSeconds()', 'setSeconds', () => import('../docs/setSeconds.md')],
  ['setTime()', 'setTime', () => import('../docs/setTime.md')],
  ['setUTCDate()', 'setUTCDate', () => import('../docs/setUTCDate.md')],
  ['setUTCFullYear()', 'setUTCFullYear', () => import('../docs/setUTCFullYear.md')],
  ['setUTCHours()', 'setUTCHours', () => import('../docs/setUTCHours.md')],
  ['setUTCMilliseconds()', 'setUTCMilliseconds', () => import('../docs/setUTCMilliseconds.md')],
  ['setUTCMinutes()', 'setUTCMinutes', () => import('../docs/setUTCMinutes.md')],
  ['setUTCMonth()', 'setUTCMonth', () => import('../docs/setUTCMonth.md')],
  ['setUTCSeconds()', 'setUTCSeconds', () => import('../docs/setUTCSeconds.md')],
  ['setYear() [已废弃]', 'setYear', () => import('../docs/setYear.md')],

  'Conversion getter',
  ['toDateString()', 'toDateString', () => import('../docs/toDateString.md')],
  ['toISOString()', 'toISOString', () => import('../docs/toISOString.md')],
  ['toJSON()', 'toJSON', () => import('../docs/toJSON.md')],
  ['toLocaleDateString()', 'toLocaleDateString', () => import('../docs/toLocaleDateString.md')],
  ['toLocaleString()', null, null],
  ['toLocaleTimeString()', null, null],
  ['toString()', null, null],
  ['toTimeString()', null, null],
  ['toUTCString()', null, null],
  ['valueOf()', null, null],
  ['toGMTString() [已废弃]', null, null],
  ['toLocaleFormat() [非标准]', null, () => null],
  ['toSource() [非标准]', null, null]
];
