export default [
  ['Array', 'Array', () => import('../docs/Array.md')],

  '属性',
  ['Array.length', 'length', () => import('../docs/length.md')],
  ['Array.prototype', 'prototype', () => import('../docs/prototype.md')],
  ['Array.prototype[@@unscopables] [es6]', 'unscopables', () => import('../docs/unscopables.md')],

  '方法',
  ['Array.from() [es6]', 'from', () => import('../docs/from.md')],
  ['Array.isArray()', 'isArray', () => import('../docs/isArray.md')],
  ['Array.observe() [已废弃]', null, null],
  ['Array.unobserve() [已废弃]', null, null],
  ['Array.of() [es6]', 'of', () => import('../docs/of.md')],

  '实例方法',
  ['Array.prototype.concat()', 'concat', () => import('../docs/concat.md')],
  ['Array.prototype.copyWithin() [es6]', 'copyWithin', () => import('../docs/copyWithin.md')],
  ['Array.prototype.entries() [es6]', 'entries', () => import('../docs/entries.md')],
  ['Array.prototype.every()', 'every', () => import('../docs/every.md')],
  ['Array.prototype.fill() [es6]', 'fill', () => import('../docs/fill.md')],
  ['Array.prototype.filter()', 'filter', () => import('../docs/filter.md')],
  ['Array.prototype.find() [es6]', 'find', () => import('../docs/find.md')],
  ['Array.prototype.findIndex() [es6]', 'findIndex', () => import('../docs/findIndex.md')],
  ['Array.prototype.forEach()', 'forEach', () => import('../docs/forEach.md')],
  ['Array.prototype.includes() [es6]', 'includes', () => import('../docs/includes.md')],
  ['Array.prototype.indexOf()', 'indexOf', () => import('../docs/indexOf.md')],
  ['Array.prototype.join()', 'join', () => import('../docs/join.md')],
  ['Array.prototype.keys() [es6]', 'keys', () => import('../docs/keys.md')],
  ['Array.prototype.lastIndexOf()', 'lastIndexOf', () => import('../docs/lastIndexOf.md')],
  ['Array.prototype.map()', 'map', () => import('../docs/map.md')],
  ['Array.prototype.pop()', 'pop', () => import('../docs/pop.md')],
  ['Array.prototype.push()', 'push', () => import('../docs/push.md')],
  ['Array.prototype.reduce()', 'reduce', () => import('../docs/reduce.md')],
  ['Array.prototype.reduceRight()', 'reduceRight', () => import('../docs/reduceRight.md')],
  ['Array.prototype.reverse()', 'reverse', () => import('../docs/reverse.md')],
  ['Array.prototype.shift()', 'shift', () => import('../docs/shift.md')],
  ['Array.prototype.slice()', 'slice', () => import('../docs/slice.md')],
  ['Array.prototype.some()', 'some', () => import('../docs/some.md')],
  ['Array.prototype.sort()', 'sort', () => import('../docs/sort.md')],
  ['Array.prototype.splice()', 'splice', () => import('../docs/splice.md')],
  [
    'Array.prototype.toLocaleString() [草案]',
    'toLocaleString',
    () => import('../docs/toLocaleString.md')
  ],
  ['Array.prototype.toSource() [非标准]', null, null],
  ['Array.prototype.toString()', 'toString', () => import('../docs/toString.md')],
  ['Array.prototype.unshift()', 'unshift', () => import('../docs/unshift.md')],
  ['Array.prototype.values() [es6]', 'values', () => import('../docs/values.md')],
  ['Array.prototype[@@iterator]()  [es6]', 'iterator', () => import('../docs/iterator.md')],
  ['get Array[@@species] [es6]', null, null]
];
